### ISSUE TITLE
_global.Performance is undefined 

### ISSUE THREAD

**Issue by dwoowb** [sinonjs/lolex#177] opened 2018-05-15 19:16 UTC
* Lolex version : 2.5.0
* Environment   : macOS 10.13.3 (High Sierra)
* Example URL   : N/A
* Other libraries you are using:

sinon 4.4.2
sinon-chai 2.14.0
mocha 5.0.1

**What did you expect to happen?**

Expected `useFakeTimers()` to work in sinon v4.4.2 the same way it did in sinon v2.0.0 which correlate to lolex v2.5.0 and v1.6.0 respectively. Found the error originating from lolex's `createClock` function.  I expected `_global.Performance` to exist [here](https://github.com/sinonjs/lolex/blob/master/src/lolex-src.js#L749) but it is undefined. Only `_global.performance` exists.

**What actually happens**

`useFakeTimers()` throws a TypeError

**How to reproduce**

Execute `useFakeTimers()`

<details>
TypeError: Cannot read property 'prototype' of undefined
      
at createClock (node_modules/lolex/src/lolex-src.js:749:45)
      at Object.install (node_modules/lolex/src/lolex-src.js:806:21)
      at exports.useFakeTimers (node_modules/sinon/lib/sinon/util/fake_timers.js:26:21)
</details>

**Comment by dwoowb** [comment] 2018-05-15 19:25
I wasn't sure if this was a sinon issue or a lolex issue, but seeing the same issue when using `lolex.install()` directly (1.6.0 vs 2.5.0)

**Comment by benjamingr** [comment] 2018-05-15 19:48
Thank you for the report and sorry for the negative experience.

This looks like a duplicate of https://github.com/sinonjs/lolex/issues/171 but you're saying it works - I'll take a look into it tomorrow or another day.

If you want to make a PR or would like help making one I'm also in favour of that :)

**Comment by dwoowb** [comment] 2018-05-15 19:55
Doh, should have checked closed issues first, apologies.

Thanks for the quick reply, I'll go ahead and check out the related issues and PRs around this. I believe this is an exact duplicate of #171, feel free to close it and if this is somehow a separate issue I can open a new issue.

**Comment by benjamingr** [comment] 2018-05-15 21:01
Thanks. Feel free to reopen if you think this is a different issue.

**Closed by benjamingr** 2018-05-15 21:01 UTC
