### ISSUE TITLE
date.set* does not respect useFakeTimers

### ISSUE THREAD

**Issue by brandonhorst** [sinonjs/lolex#41] opened 2016-02-26 02:32 UTC
Calling `date.setHours(x)` will set the hours in local time, regardless of `useFakeTimers` calls. This results in different behavior depending on the time zone in which the code is run.

Here's some code, with outputs in different time zones.

Not sure if this is a technical limitation or bad behavior.

In this example, we are faking the timers, creating a `new Date()`, and then printing it. It is created in the given time zone. Then, we call `date.setHours(8)`. Rather than setting the hour to 8am in the fake time zone, it sets it to 8am in the system local time zone every time. Below I try with my computer set to Boston time, and then SF time.

## Code

```js
const sinon = require('sinon')

function tryTime(time, name) {
  console.log(' ', name)
  const clock = sinon.useFakeTimers(time)
  const date = new Date()
  console.log(date.toUTCString())
  date.setHours(8)
  console.log(date.toUTCString())
  clock.restore()
  console.log()
}

tryTime(Date.UTC(2015, 1, 25, 12, 0, 0, 0), '7am in Boston')
tryTime(Date.UTC(2015, 1, 25, 7, 0, 0, 0), '7am in London')
tryTime(Date.UTC(2015, 1, 24, 4, 0, 0, 0), '7am in Beijing')
```

## Computer set to Boston (EST) time

```
  7am in Boston
Wed, 25 Feb 2015 12:00:00 GMT
Wed, 25 Feb 2015 13:00:00 GMT

  7am in London
Wed, 25 Feb 2015 07:00:00 GMT
Wed, 25 Feb 2015 13:00:00 GMT

  7am in Beijing
Tue, 24 Feb 2015 04:00:00 GMT
Mon, 23 Feb 2015 13:00:00 GMT
```

## Computer set to San Francisco (PST) time

```
  7am in Boston
Wed, 25 Feb 2015 12:00:00 GMT
Wed, 25 Feb 2015 16:00:00 GMT

  7am in London
Wed, 25 Feb 2015 07:00:00 GMT
Tue, 24 Feb 2015 16:00:00 GMT

  7am in Beijing
Tue, 24 Feb 2015 04:00:00 GMT
Mon, 23 Feb 2015 16:00:00 GMT
```

**Comment by fatso83** [comment] 2016-02-26 03:43
It actually took me 20 minutes of studying the output to understand what the issue was 😄.  So the second output is the same in all the cases, no matter what the time object was set to. 

So basically the setHours call needs to adjust the time relative to the created object, not the local time. Sorry for reiterating the obvious :-)

**Comment by brandonhorst** [comment] 2016-02-26 04:12
Yes precisely - sorry for not making that clearer.

**Comment by fatso83** [comment] 2016-02-26 04:13
Don't think this is a bug. I just think you need to use the right method: [setUTCHours](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/setUTCHours). 

 [setHours](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/setHours) _sets the hours for a specified date according to local time_.

**Comment by fatso83** [comment] 2016-02-26 18:01
I made an [extended version](http://output.jsbin.com/zitase/26) of your code and put it on JsBin. It seems to work as intended:
```

vanilla:	Wed, 25 Feb 2015 12:00:00 GMT
setUTCHours:	Wed, 25 Feb 2015 08:00:00 GMT
setHours:	Wed, 25 Feb 2015 07:00:00 GMT
#	#
vanilla:	Wed, 25 Feb 2015 07:00:00 GMT
setUTCHours:	Wed, 25 Feb 2015 08:00:00 GMT
setHours:	Wed, 25 Feb 2015 07:00:00 GMT
#	#
vanilla:	Tue, 24 Feb 2015 04:00:00 GMT
setUTCHours:	Tue, 24 Feb 2015 08:00:00 GMT
setHours:	Tue, 24 Feb 2015 07:00:00 GMT
```

Closing as a non-issue.

**Closed by fatso83** 2016-02-26 18:01 UTC
