### ISSUE TITLE
`loopLimit` not being used or wrong message

### ISSUE THREAD

**Issue by knod** [sinonjs/lolex#100] opened 2017-06-07 18:18 UTC
I'm not sure if my `loopLimit` isn't being used, if I'm getting the wrong message, or if I instantiate incorrectly, but I do something like this:
``` js
let lolex = require( 'lolex' );
let clock = lolex.install( 0, ['setTimeout', 'clearTimeout'], 1000000000000 );

let firstCalled = false;
let secondFunc = function () { firstCalled = true; }

// Will trigger a bunch of other `setTimeout` calls
runFirstFunc( foo, secondFunc );

setTimeout(function() {
	if ( !firstCalled ) { doSomething( bar ); }
}, 30 );

clock.runAll();
```

I use more timeouts than that, but that's the gist.

No matter how big I make the `loopLimit` number, I often, but not always, get similar messages at random points in the tests (usually one somewhere random near the end and then a bunch at the very end - the specific pattern probably has more to do with the way in which I'm running the tests) :
"(node:21049) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Aborting after running 1000 timers, assuming an infinite loop!"

***Note:*** the "node" has also been 21260, 21264, 21201, etc., and when I've had multiple messages, the rejection id changes, but the "node" number will stay the same for all of them

The number of timers is always 1000, no matter the number I set for the limit. I get the messages even if all my tests succeed.

Environment:
node v6.9.1
MacBookPro v10.11.6

This isn't super important, but even if there have been too many loops, shouldn't this fail at the same point each time? I've gotten different results even when I've run the same set of tests.

Also, is it possible to pass the loopLimit to `.runAll()`, i.e. `clock.runAll( 5000 )`? That would make more sense to me and would also be more flexible.

**Comment by knod** [comment] 2017-06-09 17:59
After trying some stuff, I think the problem may show up when `setTimeout` is used with a delay of 0.

**Comment by fatso83** [comment] 2017-07-13 13:25
If you would be able to create a minimal test case that will show the bug it would increase the chances of someone starting to work on this immensely.

**Comment by benjamingr** [comment] 2017-07-14 11:34
I was not able to reproduce this issue (with the new 2.0 syntax)

**Comment by fatso83** [comment] 2017-07-14 14:17
Then we might close it. They had [a test case](https://github.com/knod/playback/commit/699cd585e2a0b6c78cb681544aa9b0af04676543) in the open source project that references this issue. Might be a tad bit too much work to clone that and rework their tests into the new 2.0 syntax, so just assuming this works fine.

Please reopen if this bug is still lurking somewhere.

**Closed by fatso83** 2017-07-14 14:17 UTC
Labels: difficulty: medium, needs testcase, not enough information
